<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda [
<!ELEMENT agenda (contacto*)>
<!ELEMENT contacto (nombre, telefonoFijo+, telefonoMovil*)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT telefonoFijo (#PCDATA)>
<!ELEMENT telefonoMovil (#PCDATA)>
]>

<agenda>
  <contacto>
    <nombre>Ayuntamiento</nombre>
    <telefonoFijo>123456789</telefonoFijo>
  </contacto>
  <contacto>
    <nombre>Pepe</nombre>
    <telefonoFijo>987654321</telefonoFijo>
    <telefonoFijo>987654321</telefonoFijo>
    <telefonoMovil>666555444</telefonoMovil>
  </contacto>
</agenda>